apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.stream.api.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
stringData:
  {{- range $key, $value := .Values.env.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

  NATS_URL: {{ default (include "alethichelm.nats.url" $) .Values.env.variables.NATS_URL | quote }}