apiVersion: v2
name: alethic-helm
description: A Helm chart for deploying all alethic-ism modules
type: application
version: 0.1.0
appVersion: "1.0"
#icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
dependencies:
  - name: nats
    version: "1.3.2"  # Use the version you need
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
    alias: nats

  - name: nack
    version: "0.28.0"         # Replace with the correct version as needed
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nack.enabled   # Similarly, control installation via values

  - name: alethic-ism-api
    version: 0.1.0
    repository: "file://alethic-ism-api"

  - name: alethic-ism-ui
    version: 0.1.0
    repository: "file://alethic-ism-ui"

  - name: alethic-ism-monitor
    version: 0.1.0
    repository: "file://alethic-ism-monitor"

  - name: alethic-ism-state-router
    version: 0.1.0
    repository: "file://alethic-ism-state-router"

  - name: alethic-ism-usage
    version: 0.1.0
    repository: "file://alethic-ism-usage"

  - name: alethic-ism-state-sync-store
    version: 0.1.0
    repository: "file://alethic-ism-state-sync-store"

  - name: alethic-ism-processor-openai
    version: 0.1.0
    repository: "file://alethic-ism-processor-openai"

  - name: alethic-ism-processor-anthropic
    version: 0.1.0
    repository: "file://alethic-ism-processor-anthropic"


