apiVersion: v2
name: alethic-helm
description: A Helm chart for deploying all alethic-ism modules
type: application
version: 0.1.0
appVersion: "1.0"
#icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
dependencies:
  - name: alethic-ism-api
    version: 0.1.0
    repository: "file://alethic-ism-api"
