kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 31000
    protocol: TCP
  - containerPort: 80
    hostPort: 32000
    protocol: TCP
