###############################################################################
#### Local NATS Configuration values
###############################################################################
# NATS settings
nats:
  enabled: true
  natsBox:
    enabled: true
  config:
    jetstream:
      enabled: true
      memoryStore:
        enabled: true
        maxSize: 1Gi
      fileStore:
        enabled: true
        pvc:
          enabled: true
          size: 1Gi

nack:
  enabled: true
  jetstream:
    nats:
      ## TODO this needs to be set dynamically or referenced dynamically somehow
      url: "nats://test-release-nats.default.svc.cluster.local:4222"

###############################################################################
#### Other
###############################################################################
imagePullSecretName: regcred
imagePullPolicy: Always

# Default values for alethic-helm.
# nameOverride: ""
#postgres:
#  user: "alethic"
#  password: "ju$ta$imp|ep@$sw0rd"   # for production, consider using a more secure method
#  database: "alethic"
#  port: 5432

global:

  postgres:
    user: "alethic"
    password: "ju$ta$imp|epA$sw0rd"   # for production, consider using a more secure method
    database: "alethic"
    port: 5432
    initdb:
        enabled: true
        image:
            repository: krasaee/alethic-ism-db
            tag: initdb.20250407
            pullPolicy: Always

  nats:
    # url: "<overide to use your own nats server>"
    url: "{{ include \"alethichelm.nats.url\" . }}"

  # application configuration
  golang:
    dsn: "host=localhost port=5432 user=postgres password=postgres1 dbname=postgres sslmode=disable"
  python:
    dbUrl: "{{ include \"alethichelm.postgres.dburl\" . }}"
#    dbUrl: "postgresql://postgres:postgres@alethic-postgresql.svc.default.cluster.local:5432/ism"
  logging:
    level: "debug"
  routing:
    file: ".routing.yaml"
    secretName: "{{ .Release.Name }}-routes-secret"
