###############################################################################
#### Chart Enable/Disable Flags
###############################################################################
# Enable/disable individual charts
alethic-ism-api:
  enabled: true

alethic-ism-monitor:
  enabled: true

alethic-ism-processor-anthropic:
  enabled: true

alethic-ism-processor-openai:
  enabled: true

alethic-ism-processor-openrouter:
  enabled: true

alethic-ism-processor-gemini:
  enabled: true

alethic-ism-processor-python:
  enabled: true

alethic-ism-processor-mako:
  enabled: true

alethic-ism-state-router:
  enabled: true

alethic-ism-state-sync-store:
  enabled: true

alethic-ism-stream-api:
  enabled: true

alethic-ism-query-api:
  enabled: true

alethic-ism-state-online-join:
  enabled: true

alethic-ism-state-online-merge:
  enabled: true

alethic-ism-ui:
  enabled: true

alethic-ism-usage:
  enabled: true

###############################################################################
#### Local NATS Configuration values
###############################################################################
# NATS settings
nats:
  enabled: true
  natsBox:
    enabled: true
  config:
    jetstream:
      enabled: true
      memoryStore:
        enabled: true
        maxSize: 1Gi
      fileStore:
        enabled: true
        pvc:
          enabled: true
          size: 1Gi

nack:
  enabled: true
  jetstream:
    nats:
      ## TODO this needs to be set dynamically or referenced dynamically somehow
      url: "nats://test-release-nats.default.svc.cluster.local:4222"

###############################################################################
#### Other
###############################################################################
imagePullSecretName: regcred
imagePullPolicy: Always

# Default values for alethic-helm.
# nameOverride: ""
#postgres:
#  user: "alethic"
#  password: "ju$ta$imp|ep@$sw0rd"   # for production, consider using a more secure method
#  database: "alethic"
#  port: 5432

global:

  postgres:
    user: "alethic"
    password: "ju$ta$imp|epA$sw0rd"   # for production, consider using a more secure method
    database: "alethic"
    port: 5432
    sslmode: disable
    initdb:
        enabled: true
        image:
            repository: krasaee/alethic-ism-db
            # tag: latest
            # tag: initdb.20250407
            tag: initdb.latest
            pullPolicy: Always

  nats:
    # url: "<overide to use your own nats server>"
    url: "{{ include \"alethichelm.nats.url\" . }}"

  # application configuration
  golang:
    dsn: "{{ include \"alethichelm.golang.dburl\" . }}"
#    dsn: "host=localhost port=5432 user=postgres password=postgres1 dbname=postgres sslmode=disable"
  python:
    dbUrl: "{{ include \"alethichelm.postgres.dburl\" . }}"
#    dbUrl: "postgresql://postgres:postgres@alethic-postgresql.svc.default.cluster.local:5432/ism"
  logging:
    level: "debug"
  routing:
    file: ".routing.yaml"
    secretName: "{{ .Release.Name }}-routes-secret"
