{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.query.api.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "application.query.api.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host | default "localhost" }}
      http:
        paths:
          - path: /query
            pathType: Prefix
            backend:
              service:
                name: {{ include "application.query.api.fullname" . }}-service
                port:
                  number: {{ .Values.service.port | default 8080 }}
{{- end }}