apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.processor.python.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
stringData:
  {{- range $key, $value := .Values.env.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

  DATABASE_URL: {{ default (include "alethichelm.postgres.dburl" $) .Values.env.variables.DATABASE_URL | quote }}