apiVersion: v1
kind: Secret
metadata:
  # You can either hardcode the secret name or compute it dynamically.
  # Here we use a value from the values file with a fallback to a helper template.
  name: {{ include "application.processor.openrouter.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
stringData:
  {{- range $key, $value := .Values.env.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

  DATABASE_URL: {{ default (include "alethichelm.postgres.dburl" $) .Values.env.variables.DATABASE_URL | quote }}
  OPENROUTER_API_KEY: "{{ .Files.Get .Values.env.variables.OPENROUTER_API_KEY_FILE }}"
