{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname2" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "application.fullname2" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host | default "localhost" }}
      http:
        paths:
          - path: /ui(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "application.fullname2" . }}-service
                port:
                  number: {{ .Values.service.port | default 80 }}
{{- end }}
