apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname2" . }}
  namespace: "{{ .Release.Namespace }}"
stringData:
  {{- range $key, $value := .Values.env.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}