apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname2" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.labels.app }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default "30080" }}
      {{- end }}
  selector:
    app: {{ .Values.deployment.labels.app }}
