apiVersion: v1
kind: Secret
metadata:
  name: "{{ tpl .Values.global.k8s.routingSecretName . }}"
  namespace: {{ .Release.Namespace }}
stringData:
  .routing.yaml: |
    messageConfig:
      routes:
        - selector: "processor/usage"
          name: "processor_usage"
          queue: "processor_usage_queue"
          subject: "processor.usage"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "processor/state/sync"
          name: "processor_state_sync"
          queue: "processor_state_sync_queue"
          subject: "processor.state.sync"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "processor/monitor"
          name: "processor_monitor"
          queue: "processor_monitor_queue"
          subject: "processor.monitor"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "processor/state"
          name: "processor_state_state"
          jetstream_enabled: false
          subject: "processor.state.{state_id}"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "processor/state/router"
          name: "processor_state_router"
          queue: "processor_state_router_queue"
          subject: "processor.state.router"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "language/models/llama/*"
          name: "processor_models_llama"
          queue: "processor_models_llama_queue"
          subject: "processor.models.llama"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "language/models/openai/*"
          name: "processor_models_openai"
          queue: "processor_models_openai_queue"
          subject: "processor.models.openai"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "language/models/google/*"
          name: "processor_models_google"
          queue: "processor_models_google_queue"
          subject: "processor.models.google"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "language/models/anthropic/*"
          name: "processor_models_anthropic"
          queue: "processor_models_anthropic_queue"
          subject: "processor.models.anthropic"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "code/executor/python/python-executor-1.0"
          name: "processor_executor_python"
          queue: "processor_executor_python_queue"
          subject: "processor.executor.python"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "data/transformers/mixer/state-online-merge-1.0"
          name: "processor_transformer_state_online_merge"
          queue: "processor_transformer_state_online_merge"
          subject: "processor.transformer.state.online.merge"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "data/transformers/mixer/state-online-join-1.0"
          name: "processor_transform_state_online_join"
          queue: "processor_transform_state_online_join"
          subject: "processor.transform.state.online.join"
          url: {{ .Values.global.routing.natsUrl | quote }}

        - selector: "data/transformers/mixer/state-online-cross-join-1.0"
          name: "processor_transform_state_online_cross_join"
          queue: "processor_transform_state_online_cross_join"
          subject: "processor.transform.state.online.cross.join"
          url: {{ .Values.global.routing.natsUrl | quote }}
