apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.state.online.merge.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
stringData:
  {{- range $key, $value := .Values.env.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

  DSN: {{ default (include "alethichelm.postgres.dsn" $) .Values.env.variables.DSN | quote }}