apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.state.online.merge.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.deployment.labels.app }}