replicaCount: 1

image:
  repository: krasaee/alethic-ism-api
  tag: "latest"
  pullPolicy: Always

#api:
#  enableLocalAuth: true
#  enableFirebaseAuth: false

deployment:
  labels:
    app: alethic-ism-api

service:
  port: 80
  type: ClusterIP
#  nodePort: 80

ingress:
  host: "localhost"
  enabled: true

env:
  variables:
    API_ROOT_PATH: "/api/v1"
    HUGGING_FACE_TOKEN: "<enter your token here>"
    REDIS_HOST: "http://localhost:8080"
    REDIS_PORT: ""
    REDIS_PASS: ""
    LOG_LEVEL: "DEBUG"
    ROUTING_FILE: "/app/repo/.routing.yaml"
#    DATABASE_URL: ""
    SECRET_KEY: "<between 16-64 character random alphanumeric string>"
    ENABLED_LOCAL_AUTH: true
    ENABLED_FIREBASE_AUTH: false