replicaCount: 1

image:
  repository: krasaee/alethic-ism-ui
#  tag: "b619a89"
#  tag: "local"
  tag: "latest"
  pullPolicy: Always

deployment:
  labels:
    app: alethic-ism-ui

service:
  port: 80
  type: ClusterIP
#  nodePort: 80

ingress:
  host: "localhost"
  enabled: true

# Environment configuration
env:
  variables:
    PUBLIC_URL: "/ui"
    REACT_APP_ENVIRONMENT: "local"
    REACT_APP_ISM_API_BASE_URL: "http://localhost/api/v1"
    REACT_APP_ISM_QUERY_API_BASE_URL: "http://localhost/query"
#    REACT_APP_FIREBASE_API_KEY: ""
#    REACT_APP_FIREBASE_AUTH_DOMAIN: ""
#    REACT_APP_FIREBASE_PROJECT_ID: ""
#    REACT_APP_FIREBASE_STORAGE_BUCKET: ""
#    REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ""
#    REACT_APP_FIREBASE_APP_ID: ""
