apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      volumes:
        - name: routing-secret-volume
          secret:
            secretName: {{ tpl .Values.global.k8s.routingSecretName . }}
            items:
              - key: .routing.yaml
                path: .routing.yaml
        - name: module-secret-volume
          secret:
            secretName: {{ include "application.fullname" . }}
            items:
              - key: .firebase-credentials.json
                path: .firebase-credentials.json
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: routing-secret-volume
              mountPath: /app/repo/.routing.yaml
              subPath: .routing.yaml
              readOnly: true
            - name: module-secret-volume
              mountPath: /app/repo/.firebase-credentials.json
              subPath: .firebase-credentials.json
              readOnly: true
          env:
            - name: HUGGING_FACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: HUGGING_FACE_TOKEN
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: REDIS_PORT
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: REDIS_PASS
            - name: ROUTING_FILE
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: ROUTING_FILE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: SECRET_KEY
          ports:
            - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
        - name: regcred

