apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      volumes:
        - name: routing-secret-volume
          secret:
            secretName: {{ tpl .Values.global.routing.secretName . }}
            items:
              - key: .routing.yaml
                path: .routing.yaml
        - name: module-secret-volume
          secret:
            secretName: {{ include "application.fullname" . }}
            items:
              - key: .firebase-credentials.json
                path: .firebase-credentials.json
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: routing-secret-volume
              mountPath: /app/repo/.routing.yaml
              subPath: .routing.yaml
              readOnly: true
            {{- if .Values.env.variables.ENABLED_FIREBASE_AUTH }}
            - name: module-secret-volume
              mountPath: /app/repo/.firebase-credentials.json
              subPath: .firebase-credentials.json
              readOnly: true
            {{- end }}
          env:
            {{- $root := . }}
            {{- range $key, $value := .Values.env.variables }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" $root }}
                  key: {{ $key }}
            {{- end }}
            {{- if or (not .Values.env.variables.DATABASE_URL) (empty .Values.env.variables.DATABASE_URL) }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: DATABASE_URL
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
# Define custom docker registry credentials secret
#      imagePullSecrets:
#        - name: regcred

